### ISSUE TITLE
'GTMSessionFetcher.h' file not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/google-api-objectivec-client#88]
```
Commit 455 has some macro changes in GTLService.h which breaks the compilation 
of GTLTouchStaticLib on iOS 9.
```

Original issue reported on code.google.com by `an0...@gmail.com` on 21 Jul 2015 at 10:58

**Comment by Jusung** [comment]
Thanks @GoogleCodeExporter ! I've fixed this issue with your solution.

**Comment by kashif-izhar** [comment]
Thanks @GoogleCodeExporter for the solution it works!

**Comment by gnachman** [comment]
You should update https://developers.google.com/gmail/api/quickstart/ios?ver=swift to include this information.

**Comment by abdulazizalmass** [comment]
this is going to be the third time I am doing the quickstart.
apparently, not that quick

**Comment by abdulazizalmass** [comment]
If your minimum target is iOS 9 or OS X 10.11, you'll instead need to replace 
GTMHTTPFetcher with GTMSessionFetcher from 
https://code.google.com/p/gtm-session-fetcher/

I have replaced the whole source folder with the one provided above and the bug is still on
'GTMSessionFetcher.h' file not found

I am on OS X  10.11.1

Xcode: Version 7.1 (7B91b)

This is the iOS QuickStart I am trying to work out 
https://developers.google.com/google-apps/calendar/quickstart/ios?ver=swift#step_4_prepare_the_project



I am new to Github. You might find the xcodeproject here though:
https://github.com/abdulazizalmass/IOS-Quickstart-SWIFT

**Comment by MVakas** [comment]
I’m having the same issue.
Tried what @GoogleCodeExporter  has suggested but no luck.
I’m using Xcode 7.1 and OSX 10.11

**Comment by wtfroland** [comment]
Same here. Xcode 7.1.1 targeting iOS 9.1. Tried @GoogleCodeExporter's suggestion and still no luck.

**Comment by Dassine** [comment]
Same here. Tried @GoogleCodeExporter's solution ... no luck

**Comment by CTS414790** [comment]
Hi I too was facing the same issue, I tried the **@GoogleCodeExporter**  suggestions but nothing worked out. I'm posting how I resolved the issue so that it might help few fellows who might be doing same mistake which I did .
__Select the "GTL" project's "GTLTouchStaticLib" target.__
**Add the absolute path to gtm-session-fetcher/Source/ to Build Settings > User Header SearchPaths.**
But in here you need to add the exact location of your **gtm-session-fetcher - Source**  i.e.., like **user/desktop/googledriveIntegration/gtm-session-fetcher/Source/ **
Also set the absolute path for
 gtm-session-fetcher/Source/**
**google-api-objectivec-client/Source/**

**Comment by MVakas** [comment]
Hi @CTS414790  I’m trying your solution. I couldn’t get 
Also set the absolute path for
gtm-session-fetcher/Source/
google-api-objectivec-client/Source/

Can you elaborate a bit please.
Thanks.

**Comment by alexnaldo** [comment]
Same problem....

**Comment by alexnaldo** [comment]
More explain how to solve the problem :
http://alessiopapazzoni.com/2015/11/12/swift-using-google-endpoints-in-an-ios-client/

**Comment by CTS414790** [comment]
Hi @MVakas my solution was simple just to replace the 
** gtm-session-fetcher/Source/google-api-objectivec-client/Source/  **
with the exact location it is placed in your PC . just drag the  Source file into the terminal and you could the  location schema and just replace the above with the one you got it in your terminal . As of me I have placed the ** gtm-session-fetcher - Source ** on my desktop in the folder named ** googledriveIntegration** so my schema is like **user/desktop/googledriveIntegration/gtm-session-fetcher/Source/ **

There might be another problem also make sure that the files are accessed by the source controller.
If you see '?' or the  '--' at the right of your file in the Xcode . just click the right mouse button above that file, click on the source controller and add the files to source controller this might also be the reason for the missing files.

**Comment by MVakas** [comment]
![screen shot 2015-12-12 at 11 28 42 am](https://cloud.githubusercontent.com/assets/7447077/11760625/882f521e-a0c3-11e5-9833-23fd88b22402.png)
Still struggling :(

**Comment by MVakas** [comment]
Now getting 
'GTMOAuth2ViewControllerTouch.h' file not found

**Comment by alexnaldo** [comment]
I did exactly like the above link and worked fine! Is not to change the search path and change the path it self.

**Comment by pr0gramm3r8hai** [comment]
Having Same Problem here :(

**Comment by MVakas** [comment]
I have given up on this.

**Comment by thomasvl** [comment]
Git submodules in now to pull deps.  So thins should resolve the issue for folks.

**Comment by thomasvl** [comment]
As mentioned, we've got git submodules in for folks that want to just use the project files checked in, and there are cocoapods for the developers that want that.  If there are are errors in this project, please let us know.  If they are issues on other sites, also let us know and we'll see what we can do to help.  There is a comment above about https://developers.google.com/gmail/api/quickstart/ios?ver=swift not being correct, just took a quick look, and it does refer to the correct projects.  If there are some specific issues with that site (or others), let us know and we'll try to relay things along to those teams.

**Comment by jordanform** [comment]
[](https://alessiopapazzoni.com/2015/11/12/swift-using-google-endpoints-in-an-ios-client/)
Just reference link and works for me, thx!

**Comment by AlexeyPoldeo** [comment]
To get GTMSessionFetcher.h, just add this project as dependency into XCode project: https://github.com/google/gtm-session-fetcher

**Comment by anuragedushire** [comment]
Someone should update - https://cloud.google.com/appengine/docs/java/endpoints/calling-from-ios

**Comment by thomasvl** [comment]
@anuragedushire I'm not making the connection between this issue (using/finding the SessionFetcher) and the doc you linking.  I'm assuming you are just talking about that guide generally being wrong since it is trying to use a RPC document instead of REST?  I've filed a bug against that team to get that updated.  If you comment was about something else, please open a new issue to detail what your probably is.

**Comment by anuragedushire** [comment]
Yes, rest vs rpc is one. Additionally the document should also mention to do 'git submodule init/update' for things to compile.

**Comment by thomasvl** [comment]
Thanks, added that to the bug for the page update.

**Comment by fanqiguoguo** [comment]
What is this excuse me?Confused for a long time...[
![1111111](https://cloud.githubusercontent.com/assets/20611833/21894311/a8a180d2-d919-11e6-9673-0e7df9f8079b.png)
](url)

**Comment by thomasvl** [comment]
@fanqiguoguo did you fetch the git submodules or not?

**Comment by bestmajesty** [comment]
@fresh83 can you tell me how did you solve this? I got 4 files missed using BloggerSample now, GTMSessionFetcher.h , GTMSessionUploadFetcher.h, GTMSessionFetcherService.h, GTMSessionFetcherLogging.h.  And I dont understand thomasvl comments , he didn't explain the reason at all. If you understand already, can you explain for me? thank you.

**Comment by bestmajesty** [comment]
@fresh83  I worked it out! wow,  use git submodule int , then git  submodule update,  will fix this!
